#!/usr/bin/env python3
"""Best-effort write guard for governed edits."""

from __future__ import annotations

import argparse
import fnmatch
import sys
from pathlib import Path
from typing import Any

sys.dont_write_bytecode = True

from governance_artifacts import read_json


def project_root_from_task_dir(task_dir: Path) -> Path:
    resolved = task_dir.resolve()
    if resolved.parent.name != "tasks" or resolved.parent.parent.name != ".project-governance":
        raise ValueError("task directory must be .project-governance/tasks/<TaskID>")
    return resolved.parent.parent.parent


def is_relative_to(child: Path, parent: Path) -> bool:
    try:
        child.resolve().relative_to(parent.resolve())
        return True
    except ValueError:
        return False


def task_allowed_paths(task_dir: Path) -> tuple[Path, list[str]]:
    before = task_dir / "before.json"
    minimal = task_dir / "task-record.json"
    if before.is_file():
        if minimal.is_file():
            print(
                "WARNING: task-record.json exists beside before.json; using the full carrier allowed_paths.",
                file=sys.stderr,
            )
        record = read_json(before)
        return project_root_from_task_dir(task_dir), list(record["scope"]["allowed_paths"])
    if minimal.is_file():
        record = read_json(minimal)
        return project_root_from_task_dir(task_dir), list(record["task_contract"]["allowed_paths"])
    raise FileNotFoundError("no TaskContract or Minimal record exists")


def path_matches_allowed(target: Path, project_root: Path, allowed: str) -> bool:
    allowed_path = Path(allowed)
    target_resolved = target.resolve()
    if allowed_path.is_absolute():
        allowed_resolved = allowed_path.resolve()
        return target_resolved == allowed_resolved or is_relative_to(target_resolved, allowed_resolved)
    relative = target_resolved.relative_to(project_root.resolve()).as_posix()
    pattern = allowed_path.as_posix().rstrip("/")
    if fnmatch.fnmatchcase(relative, pattern) or fnmatch.fnmatchcase(relative, pattern + "/**"):
        return True
    allowed_resolved = (project_root / allowed_path).resolve()
    return target_resolved == allowed_resolved or is_relative_to(target_resolved, allowed_resolved)


def evaluate(target: Path, task_dir: Path | None) -> tuple[bool, str]:
    target_resolved = target.resolve()
    parts = target_resolved.parts
    if ".project-governance" in parts and target_resolved.name == "project-state.json":
        return False, "project-state.json is generated; use rebuild_project_state.py"
    if target_resolved.name == "embedded-manifest.json" and "assets" in parts and "runtime" in parts:
        return False, "embedded-manifest.json hashes must be regenerated by sync_embedded_references.py"
    if task_dir is None:
        return True, "WARNING: no task package supplied; write guard did not enforce allowed_paths"
    task_dir_resolved = task_dir.resolve()
    if is_relative_to(target_resolved, task_dir_resolved):
        return True, "allowed: target is inside the active task directory"
    project_root, allowed_paths = task_allowed_paths(task_dir_resolved)
    if not allowed_paths:
        return True, "WARNING: task has no allowed_paths; write guard did not block"
    for allowed in allowed_paths:
        try:
            if path_matches_allowed(target_resolved, project_root, str(allowed)):
                return True, f"allowed: target matches allowed_path {allowed}"
        except ValueError:
            continue
    return False, "target is outside the active task directory and allowed_paths"


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--task-dir", type=Path)
    parser.add_argument("path", type=Path)
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    try:
        allowed, message = evaluate(args.path, args.task_dir)
        if allowed:
            stream = sys.stderr if message.startswith("WARNING:") else sys.stdout
            print(message, file=stream)
            return 0
        print(f"REFUSED: {message}", file=sys.stderr)
        return 1
    except Exception as exc:
        print(f"WARNING: write guard failed open: {exc}", file=sys.stderr)
        return 0


if __name__ == "__main__":
    raise SystemExit(main())
